name: testando a regra de protection role

on:
  branch_protection_rule:
    types: [created, edited, deleted]


jobs:
  print-modifications:
    runs-on: ubuntu-latest
    steps:

      - name: Avisa sobre a modificacao 
        run: echo ¨Este Workflow foi trigado pois a regra da protection role foi altarada.¨