name: Desafio Aula01

on:
  workflow_dispatch
  
    inputs:
      docker_image:
        description: 'Digite o nome da imagem Docker'
        required: true
        
jobs:
  run-image-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Ler input
        run: |
          IMAGE="${{ github.event.inputs.docker_image }}"
          echo "Usando imagem $IMAGE"

       