name: DesafioAula01

on:
  workflow_dispatch:
    inputs:
      docker-image:
        description: "Qual imagem Docker deseja fazer o download?"
        required: true
        type: string

jobs:
  desafio_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Verificando a Imagem!
        run: echo "Olá, ${{ github.event.inputs.docker-image }}!"

      - name: Fazendo Download da imagem Docker.
        run: docker pull ${{ github.event.inputs.docker-image }}

      - name: Listando as imagens docker.
        run: docker images