name: Vendo arquivos compartilhados entre steps

on:
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versão do ubuntu
        run: cat /etc/os-release

      - name: Exibir uma mensagem
        run: echo "Estou fazendo o Curso de Github Actions da Linuxtips" > ${{ github.workspaces }}/mensagem.txt

      - uses: actions/upload-artifact@v4
        with:
          name: strigus
          path: ${{ github.workspaces }}/mensagem.txt

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:

      - name: Ver o conteudo do diretorio
        run: ls -lah && ls -lah ./strigus/

      - uses: actions/download-artifact@v4
        with:
          name: strigus
          path: mensagem.txt
      
      - name: Acessa arquivo mensagem
        run: mv strigus/mensagem.txt . && rm -rf ./strigus/mensagem.txt

      - name: Ver o conteudo do diretorio
        run: ls -lah && ls -lah ./strigus/

      - name: Ler arquivo
        run: cat mensagem.txt

      
